source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PXImageViewExample' do
  pod "PXImageView", :path => "../"
end

target 'Tests' do
  pod "PXImageView", :path => "../"
end

target 'PXImageViewSwift' do
    pod "PXImageView", :path => "../"
end

target 'PXImageViewSwiftTests' do
    pod "PXImageView", :path => "../"
end
